GET http://localhost:9999/products
Authorization: Bearer 


###

POST http://localhost:9998/login
Content-Type: application/json

{
    "username": "whomever" 
}

###

POST http://localhost:9998/token
Content-Type: application/json

{
    "token": ""
}

###

DELETE http:/localhost:9998/logout
Content-Type: application/json

{
    "token": ""
}